feat: workflow page added
amychisholm03/hp-capstone-2025-frontend pull request #12
Opened 2024-11-01 19:43 UTC by Gabrielle-Barling

I added the workflows page with vuetify. User can select a previous workflow (only default for now) or create a new workflow.

2024-11-01 20:17 UTC, CadeTormanen submitted a review, later dismissed
lgtm!

2024-11-02 00:57 UTC, amychisholm03 requested changes
Please address the merge conflicts by using the updated sidebar with the `SimulationReports` routing.

2024-11-05 17:44 UTC, amychisholm03 approved these changes, later dismissed

2024-11-05 17:44 UTC, amychisholm03 commented on vue-project/src/components/PrintJobs.vue
> +    const url = "http://54.200.253.84:80/createJob";
Might want to use `api.wsuv-hp-capstone.com` instead of IP, but we can change that later

2024-11-05 23:33 UTC, amychisholm03 approved these changes
Saw this IRL looks good

2024-11-06 00:16 UTC, CadeTormanen approved these changes
lgtm

2024-11-06 00:17 UTC, merged